
apiVersion: apps/v1
kind: Deployment
metadata:
  name: make5
  labels:
    app: make5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: make5
  template:
    metadata:
      labels:
        app: make5
    spec:
      containers:
        - name: make5
          image: ddatsko/boost_concurrent_make:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
