
apiVersion: v1
kind: Service
metadata:
  name: make-service5
spec:
  type: LoadBalancer
  selector:
    app: make5
  ports:
    - name: main
      protocol: TCP
      port: 443
      targetPort: 3000
